spring:
  application:
    name: ApiGetway

server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  # Enable service discovery for gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: gestion-pfe
          uri: lb://GESTION-PFE
          predicates:
            - Path=/pfe/**

        - id: gestion-courses
          uri: lb://GESTION-COURSES
          predicates:
            - Path=/courses/**,/course-resources/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: reclamation-service
          uri: lb://RECLAMATION-SERVICE
          predicates:
            - Path=/api/reclamations/**
